export const fallbackCatalog = [
  {
    id: 1,
    category: { id: 4, name: 'Camisetas' },
    name: 'Camisa Oversize Blanca',
    description: 'Camisa unisex estilo oversize en tela suave, ideal para outfits callejeros.',
    price: 299,
    image_path: 'uploads/1765570943_adidas.jpg',
    stock: 12,
    sizes: ['M', 'XL'],
    brand: 'Adidas',
  },
  {
    id: 2,
    category: { id: 5, name: 'Sudaderas' },
    name: 'Sudadera Negra',
    description: 'Sudadera negra con diseno minimalista, comoda y ligera.',
    price: 450,
    image_path: 'uploads/1765572693_sudadera_negra.jpg',
    stock: 8,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 3,
    category: { id: 3, name: 'Pantalones' },
    name: 'Pantalon Cargo Arena',
    description: 'Pantalon cargo color arena con multiples bolsas y ajuste en tobillos.',
    price: 520,
    image_path: 'uploads/1765572773_pantalonn.jpg',
    stock: 6,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: 4,
    category: { id: 3, name: 'Pantalones' },
    name: 'Jeans Azul',
    description: 'Jeans clasico azul, corte baggy, tela stretch.',
    price: 399,
    image_path: 'uploads/1765572872_jeans.jpg',
    stock: 9,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 5,
    category: { id: 6, name: 'Accesorios' },
    name: 'Gorra Negra Street',
    description: 'Gorra negra estilo urbano, diseno bordado frontal.',
    price: 180,
    image_path: 'uploads/1765574395_GORRA.jpg',
    stock: 15,
    sizes: ['Unitalla'],
  },
  {
    id: 6,
    category: { id: 4, name: 'Camisetas' },
    name: 'Playera Grafica Anime',
    description: 'Playera de algodon con estampado inspirado en estetica anime.',
    price: 250,
    image_path: 'uploads/1765574444_anime.jpg',
    stock: 10,
    sizes: ['XS', 'S', 'M', 'L'],
  },
  {
    id: 7,
    category: { id: 2, name: 'Blusas' },
    name: 'Top Deportivo Rosa',
    description: 'Top ligero y transpirable para entrenamiento o uso casual.',
    price: 220,
    image_path: 'uploads/1765574461_top.jpg',
    stock: 7,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: 8,
    category: { id: 3, name: 'Pantalones' },
    name: 'Shorts Deportivos Unisex',
    description: 'Short deportivo comodo con tela fresca.',
    price: 210,
    image_path: 'uploads/1765574545_shorts.jpg',
    stock: 11,
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 9,
    category: { id: 6, name: 'Accesorios' },
    name: 'Mochila Urbana Negra',
    description: 'Mochila resistente con bolsillos multiples y estilo urbano.',
    price: 550,
    image_path: 'uploads/1765574568_mochila.jpg',
    stock: 4,
    sizes: ['Unitalla'],
  },
  {
    id: 10,
    category: { id: 5, name: 'Sudaderas' },
    name: 'Chamarra Rompevientos Azul',
    description: 'Rompevientos ligero resistente al agua, ideal para clima fresco.',
    price: 480,
    image_path: 'uploads/1765574586_rompevientos.jpg',
    stock: 5,
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: 11,
    category: { id: 3, name: 'Pantalones' },
    name: 'Joggers Grises',
    description: 'Joggers unisex color gris, comodos y combinables.',
    price: 330,
    image_path: 'uploads/1765574663_joggers .jpg',
    stock: 8,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: 12,
    category: { id: 2, name: 'Blusas' },
    name: 'Blusa Casual Beige',
    description: 'Blusa suave con corte relajado y color beige clasico.',
    price: 260,
    image_path: 'uploads/1765574685_camisa.jpg',
    stock: 9,
    sizes: ['S', 'M', 'L'],
  },
  {
    id: 13,
    category: { id: 6, name: 'Accesorios' },
    name: 'Cinturon Negro Clasico',
    description: 'Cinturon de piel sintetica color negro, hebilla metalica.',
    price: 150,
    image_path: 'uploads/1765574706_cinturon.jpg',
    stock: 20,
    sizes: ['Unitalla'],
  },
  {
    id: 14,
    category: { id: 5, name: 'Sudaderas' },
    name: 'Hoodie Rosa Pastel',
    description: 'Hoodie unisex color rosa pastel con bolsas frontales.',
    price: 470,
    image_path: 'uploads/1765574761_hoddie.jpg',
    stock: 7,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 15,
    category: { id: 1, name: 'Faldas' },
    name: 'Falda Plisada Negra',
    description: 'Falda juvenil plisada color negro, tela ligera y comoda.',
    price: 320,
    image_path: 'uploads/1765574781_falda.jpg',
    stock: 6,
    sizes: ['XS', 'S', 'M'],
  },
]
